[versions]
commons-compress = "1.26.1"
androidx-test = "1.6.2"
androidx-test-junit = "1.2.1"
android-gradle-plugin = "8.1.1"
native-utils = "1.0.0"

[libraries]
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
native-utils = { module = "com.github.evermind-zz.osext:native-utils", version.ref = "native-utils" }
